"""add knowledge_bases documents segments tables

Revision ID: 7adbcdf34d61
Revises: 7fe093d4252d
Create Date: 2026-09-23 09:01:20.742680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7adbcdf34d61'
down_revision: Union[str, Sequence[str], None] = '7fe093d4252d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('name', sa.String(length=200), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: ready/indexing/error/empty'),
    sa.Column('document_count', sa.Integer(), nullable=False, comment='文档数量'),
    sa.Column('segment_count', sa.Integer(), nullable=False, comment='分段数量'),
    sa.Column('embedding_model', sa.String(length=100), nullable=False, comment='向量化模型'),
    sa.Column('chunk_method', sa.String(length=20), nullable=False, comment='分段方式: fixed/sentence/paragraph'),
    sa.Column('chunk_size', sa.Integer(), nullable=False, comment='分段大小（tokens）'),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False, comment='重叠大小（tokens）'),
    sa.Column('retrieval_strategy', sa.String(length=20), nullable=False, comment='检索策略: vector/fulltext/hybrid'),
    sa.Column('top_k', sa.Integer(), nullable=False, comment='返回结果数'),
    sa.Column('similarity_threshold', sa.Float(), nullable=False, comment='相似度阈值'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=False, comment='所属知识库ID'),
    sa.Column('file_name', sa.String(length=500), nullable=False, comment='文件名'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件类型: pdf/docx/md/txt/html/csv'),
    sa.Column('file_size', sa.String(length=50), nullable=True, comment='文件大小'),
    sa.Column('minio_path', sa.String(length=1000), nullable=True, comment='MinIO 存储路径'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='处理状态: pending/processing/completed/failed'),
    sa.Column('segment_count', sa.Integer(), nullable=False, comment='分段数量'),
    sa.Column('word_count', sa.Integer(), nullable=False, comment='字数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True, comment='上传者'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='处理完成时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=False, comment='所属知识库ID'),
    sa.Column('document_id', sa.BigInteger(), nullable=False, comment='所属文档ID'),
    sa.Column('position', sa.Integer(), nullable=False, comment='在文档中的位置序号'),
    sa.Column('content', sa.Text(), nullable=False, comment='分段内容'),
    sa.Column('word_count', sa.Integer(), nullable=False, comment='字数'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Token 数'),
    sa.Column('hit_count', sa.Integer(), nullable=False, comment='检索命中次数'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    op.drop_table('documents')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
